### ISSUE TITLE
Support Jetstream

### ISSUE THREAD

**Issue by marijnbent** [laravel/spark-aurelius-mollie#6]
I saw on Twitter that you were going to add support for Jetstream. This issue can be used to keep track.

Questions though: is it possible to import the jetstream files in the future, if the project is initiated now?

**Comment by driesvints** [comment]
@sandervanhooft can this issue be closed as well as the issue tracker since this version of Spark Mollie is discontinued?

**Comment by sandervanhooft** [comment]
Absolutely, thanks @driesvints !
